# Generated by Django 5.0.9 on 2024-12-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_update_count',
            field=models.IntegerField(default=0, verbose_name='patient_update_count'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('REPORTED', 'REPORTED'), ('MISSED', 'MISSED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10, verbose_name='status'),
        ),
    ]
