# Generated by Django 5.0.9 on 2024-12-20 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_patient_update_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this model should be treated as active or not.', verbose_name='is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('advertise_image', models.FileField(blank=True, null=True, upload_to='advertise_images/%Y/%m/%D/', verbose_name='advertise_image')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('redirect_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='redirect_link')),
                ('redirect_link_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='redirect_link_text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Advertise',
                'verbose_name_plural': 'Advertises',
                'ordering': ('created_at',),
            },
        ),
    ]
