# Generated by Django 5.0.9 on 2024-12-07 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_patients_options_patients_patient_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('A', 'A'), ('B', 'B'), ('O', 'O')], max_length=10, null=True, verbose_name='blood_group'),
        ),
        migrations.AddField(
            model_name='patients',
            name='hemoglobin',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS')], max_length=10, null=True, verbose_name='hemoglobin'),
        ),
        migrations.AddField(
            model_name='patients',
            name='rhesus_factor',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE')], max_length=10, null=True, verbose_name='rhesus_factor'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='type',
            field=models.CharField(choices=[('NURSE', 'NURSE'), ('GENERALIST', 'GENERALIST'), ('SPECIALIST', 'SPECIALIST'), ('CASHIER', 'CASHIER')], default='SPECIALIST', max_length=10, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this model should be treated as active or not.', verbose_name='is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='staffs',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='actors.speciality'),
        ),
    ]
