# Generated by Django 5.0.9 on 2024-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_patients_parent_relation_typ_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='title',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Pr', 'Pr')], default='Dr', max_length=10, verbose_name='title'),
        ),
    ]
