# Generated by Django 5.0.9 on 2024-12-20 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_staffs_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/%Y/%m/%D/', verbose_name='diploma'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='professional_card',
            field=models.FileField(blank=True, null=True, upload_to='professional_cards/%Y/%m/%D/', verbose_name='professional_card'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='close_time'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY'), ('HOLIDAYS', 'HOLIDAYS')], max_length=20, null=True, verbose_name='day_of_week'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='open_time'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_time'),
        ),
        migrations.CreateModel(
            name='MedicalFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this model should be treated as active or not.', verbose_name='is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='medical_history')),
                ('ongoing_treatments', models.TextField(blank=True, null=True, verbose_name='ongoing_treatments')),
                ('recent_consultations_summary', models.TextField(blank=True, null=True, verbose_name='recent_consultations_summary')),
                ('lifestyle_and_habits', models.TextField(blank=True, null=True, verbose_name='lifestyle_and_habits')),
                ('emergency_contact', models.TextField(blank=True, null=True, verbose_name='emergency_contact')),
                ('medical_folder_password', models.CharField(blank=True, max_length=6, null=True, verbose_name='medical_folder_password')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_folder', to='actors.patients')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'MedicalFolder',
                'verbose_name_plural': 'MedicalFolders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this model should be treated as active or not.', verbose_name='is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='document_name')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%D/', verbose_name='document')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('medical_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='actors.medicalfolder')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('-created_at',),
            },
        ),
    ]
