# Generated by Django 5.0.9 on 2024-12-20 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_staffs_diploma_staffs_professional_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='presentation',
            field=models.TextField(blank=True, null=True, verbose_name='presentation'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this model should be treated as active or not.', verbose_name='is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('payment_type', models.CharField(choices=[('ORANGE_MONEY', 'ORANGE_MONEY'), ('MTN_MOBILE_MONEY', 'MTN_MOBILE_MONEY')], default='ORANGE_MONEY', max_length=20, verbose_name='payment_type')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='actors.staffs')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'PaymentMethod',
                'verbose_name_plural': 'PaymentMethods',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this model should be treated as active or not.', verbose_name='is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.FloatField(default=0.0, verbose_name='amount')),
                ('pricing_type', models.CharField(choices=[('CHILD', 'CHILD'), ('ADULT', 'ADULT'), ('NORMAL', 'NORMAL'), ('DISABLED', 'DISABLED')], default='NORMAL', max_length=10, verbose_name='pricing_type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_pricing', to='actors.staffs')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StaffPath',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this model should be treated as active or not.', verbose_name='is active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('description', models.TextField(verbose_name='description')),
                ('start_year', models.IntegerField(verbose_name='start_date')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='end_date')),
                ('path_type', models.CharField(choices=[('FORMATION', 'FORMATION'), ('EXPERIENCE', 'EXPERIENCE')], default='FORMATION', max_length=20, verbose_name='path_type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_paths', to='actors.staffs')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'StaffPath',
                'verbose_name_plural': 'StaffPaths',
                'ordering': ('-created_at',),
            },
        ),
    ]
