# Generated by Django 5.0.9 on 2024-11-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_patients_options_patients_patient_parent_and_more'),
        ('users', '0002_user_patient_otp_profile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='actors.staffs'),
        ),
    ]
