# Generated by Django 5.0.9 on 2024-12-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_patients_parent_relation_typ_countries'),
        ('users', '0003_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='actors.countries'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quarter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='quarter'),
        ),
    ]
